# -*- coding: utf-8 -*-
"""modules/__init__

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rA-o93ZgrtGZhUdMTRXyQ7YQyIn9S-05
"""

# modules/__init__.py
# This file makes "modules" a Python package
# so you can import like: from modules import attrition_tab



