# -*- coding: utf-8 -*-
"""tabs/__init__

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rA-o93ZgrtGZhUdMTRXyQ7YQyIn9S-05
"""

# tabs/__init__.py
# This file makes "tabs" a Python package
# so app.py can import tab functions



